### ISSUE TITLE
README

### ISSUE THREAD

**Issue by lbguilherme** [txtdirect/txtdirect#1]
Please add a README, otherwise https://caddyserver.com/docs/http.txtdirect, which links to https://github.com/txtdirect/txtdirect/blob/master/README.md for docs will be broken.

Some basic info about what this plugin do and how to configure it will be appreciated.

**Comment by stp-ip** [comment]
Sorry this middleware is still a work in progress and wasn't completely ready for being listed. We'll definitely provide more documentation etc. in the following days/weeks.
