### ISSUE TITLE
[gometa] Path based routing support for packages

### ISSUE THREAD

**Issue by stp-ip** [txtdirect/txtdirect#116]
**Is this a BUG REPORT or FEATURE REQUEST?**:
feature

**What happened**:
Currently we don't support path based gometa vanity urls.

**What you expected to happen**:
Support path based gometa vanity urls.

**Comment by erbesharat** [comment]
Can you describe the feature a little more? A request flow example would be great.

**Comment by stp-ip** [comment]
So currently what works is:
```
go get txtdirect.example.test/some/pkg/
same as: go get github.com/txtdirect/txtdirect/some/pkg/
```

What would also be good to support would be:
```
go get pkg.example.test/txtdirect/some/pkg/
same as: go get github.com/txtdirect/txtdirect/some/pkg/
```

Or even root level support:
```
go get example.test/txtdirect/some/pkg/
same as: go get github.com/txtdirect/txtdirect/some/pkg/
```

This needs some discussion on how path based routes might be supported for other types.

**Comment by stp-ip** [comment]
That would conflate path and the specific types. If it's a path based thing it should in the optimal case be `rec.Type=path` only and then get the _redirect record parse the type and either handle it directly or call out to gometa and it's own path function if necessary. So my thought would be:

if `gometa`, then redirect using gometa function.
if `path`, then check subdomain according to path rules, if type gometa use the data from that new record to redirect accordingly.

In my view with gometa we wouldn't need much additional code in path.
Happy to discuss this in more detail.
