### ISSUE TITLE
Using wildcard domains with CNAME breaks TXT record usage

### ISSUE THREAD

**Issue by stp-ip** [txtdirect/txtdirect#139]
**Is this a BUG REPORT or FEATURE REQUEST?**:
bug

**What happened**:
When using a DNS config as shown below it will respond any TXT record requests such as "_redirect.sourcecode.hosting" with the TXT records of the txtdirect.io domain. In this case google verification and mail TXT records. This results in a multiple records returned error.
```
*.sourcecode.hosting. 86400 IN CNAME txtdirect.io.
_redirect._.sourcecode.hosting. 86400 IN TXT "v=txtv0;to=https://www.google.com/search?btnI=1&q={label1};type=host"
```

**What you expected to happen**:
Not sure. It works as one would expect from DNS, but it breaks the general wildcard idea to catch all subdomains and use this in a redirect.

**How to reproduce it (as minimally and precisely as possible)**:

**Anything else we need to know?**:
Any other solution besides documenting this edge case and using A records instead of a CNAME?

One other option would be to notice CNAME records and trigger an error for them. This would limit the use case of CNAME for TXT records, which is a nice way to delegate a text record.
Example:
_redirect.member1.team.okkur.io could have a CNAME such as _redirect.okkur.member1.com.
This way okkur delegates the redirect record to member1's domain. That way any changes can easily be done on his side without okkur's involvement.

**Comment by captn3m0** [comment]
This seems like the closest issue to ask this question:

I haven't tested this, but are CNAMEs resolved as part of the TXT resolution? For eg, if I setup

`l.x.com CNAME txtd.io`
`_redirect.l.x.com TXT v=txtv0;to=https://example.com;type=path`
`_redirect.path.l.x.com TXT v=txtv0;to=https://example.com/nowhere;type=host`

and then point `location.x.com` like:

`location.x.com CNAME l.x.com`

would `location.x.com/path` redirect to `example.com/nowhere`?

**Comment by stp-ip** [comment]
This bug was fixed in latest master.

Now to the question. Happy for you to create separate issues for such things.
To answer it here. 
This would not work from a DNS perspective. A CNAME is only an alias for one zone.
It can be used for TXT records in this way so:
```
txt.example.test.                IN TXT "127.0.0.1"
cname.example.test.              IN CNAME txt.example.test.
```
`dig TXT cname.example.test would return the TXT record`

What can be done would be chaining redirects. Not perfect, but works.
```
location.x.com CNAME txtd.io
_redirect.location.x.com TXT "v=txtv0;to=https://l.x.com{uri};type=host"

l.x.com CNAME txtd.io
_redirect.l.x.com TXT "v=txtv0;to=https://example.com;type=path"
_redirect.path.l.x.com TXT "v=txtv0;to=https://example.com/nowhere;type=host"
```
Sidenote: Each additional redirect adds overhead so for legacy redirects that's fine or, if performance is not important. The more used domain should definitely be the one using path and not the one chaining to another one.
