### ISSUE TITLE
[gometa] document go source support for github

### ISSUE THREAD

**Issue by stp-ip** [txtdirect/txtdirect#164]

**Comment by PHANTOM956** [comment]
@stp-ip i want to do this.. can i be assigned to this...???

**Comment by stp-ip** [comment]
Sure. The relevant PR is: #160
Website code is at: github.com/txtdirect/website.

We use un unreleased version of Syna (syna.okkur.io) with the [content](https://syna-demo.okkur.io/fragments/content/) + [toc](https://syna-demo.okkur.io/fragments/toc/) fragment.

If you want you can upgrade Syna to master and use the latest sticky feature for the toc before adding the go source documentation.

Also not yet sure, where that documentation makes the most sense. Probably a small note on the examples page and a more elaborate docs on the function of each type? Currently most of it is deployment configuration, specification and examples.

Happy to hear your thoughts and welcome to contribute.

**Comment by stp-ip** [comment]
Also we have some left over docs within https://github.com/txtdirect/txtdirect, which might be removed and/or migrated #165

**Comment by stp-ip** [comment]
Done
