### ISSUE TITLE
[prometheus] Discuss adding path metric per host

### ISSUE THREAD

**Issue by stp-ip** [txtdirect/txtdirect#174]
**Is this a BUG REPORT or FEATURE REQUEST?**:
feature

**What happened**:
We currently don't have any insight from within the application how many redirects per path we do.

**What you expected to happen**:
Count path for each host.

Suggestion:
```
 txtdirect_redirect_$host_path_count_total{path}
```

Example:
```
txtdirect_redirect_example.com_path_count_total{path="/"} = 2
txtdirect_redirect_example.com_path_count_total{path="/pricing"} = 9
txtdirect_redirect_example.com_path_count_total{path="/blog"} = 1
txtdirect_redirect_example.com_path_count_total{path="/txtdirect"} = 5
```

Another approach:
```
 txtdirect_redirect_path_count_total{host,path}
```

Example:
```
txtdirect_redirect_path_count_total{host="example.de",path="/"} = 2
txtdirect_redirect_path_count_total{host="example.com",path="/"} = 5
txtdirect_redirect_path_count_total{host="example.com",path="/txt"} = 21
txtdirect_redirect_path_count_total{host="example.com",path="/blog"} = 29
```

The second approach seems a bit cleaner, but not sure, about the downsides still researching. Would love your thoughts.

The second approach is also more similar to how caddy prometheus and others are doing it and also dynamic naming is discouraged.

**Comment by alarsyo** [comment]
The second one looks cleaner indeed. Though I don't know enough about Prometheus to think about the eventual downsides.

And yes, that definitely looks like something we need to get metrics on in the long run :)
