### ISSUE TITLE
[code] Use temporary redirect as default redirect code

### ISSUE THREAD

**Issue by stp-ip** [txtdirect/txtdirect#187]
**What happened**:
The default `code`, when not set is 301 aka a permanent redirect.

**What you expected to happen**:
Maybe we should use 302 aka a temporary redirect.

**Anything else we need to know?**:
Upside: Permanent redirect needs to be done explicitly so browser don't cache the default response indefinitely.
Downside: For permanent redirects it adds more configuration in each record.

Not sure, which is the main use case. In our internal use it's mostly 301, but I just ran into an issue, where I still had a cached redirect in chrome as chrome caches 301 redirects indefinitely it seems. Aka until the cache is cleaned.

301 vs 302 as default?
Arguments? Suggestions?

**Comment by stp-ip** [comment]
To add to this:

Firefox and Chrome both cache the 301 indefinitely. So one missing code=302, might redirect indefinitely to the wrong place.

We have a few options in my thinking:
* default to 302 redirects
* default to 301 redirects, but add a cache header to prevent indefinitely creating issues (maybe a week? 604800s)
* default to 302 redirects and add a cache header to 301 redirects to prevent completely messing up (at least it's then only broken for a week or what we set)

I think defaulting to 302 + setting a fallback cache header is a good solution.
What are your thoughts? What about the length of the cache timeout? I think with 302 being the default and the necessity to explicitly set 301, a week or two of a timeout makes sense. This reduces the load on "legacy"/permanent redirects, while still giving the option to not break things indefinitely.

**Comment by erbesharat** [comment]
I think defaulting to 302 is a good solution too. And the one-week cache age makes sense.
