### ISSUE TITLE
[gometa, gomods] Clarify usage and interaction

### ISSUE THREAD

**Issue by stp-ip** [txtdirect/txtdirect#189]
Trying to clean up my thoughts and open for suggestions or clarifying questions on this front.

Gometa is used to create vanity urls for packages and package imports.
import "go.example.test/pkg/cmd"
go get go.example.test/pkg/cmd

Currently gometa only has information on where the source code is located aka it enables tools to look up the current source code storage.

To enable tools to jump right into downloading a prepared and cached module, we would need to support the "mod" vcs, which then links to gomods proxy/storage location.

Open questions:
* should this be a specific storage location aka S3, GCS etc.?
* should this be a gomods proxy?

How would gomods type be used? Basically enabling having a vanity url for a globally accessible gomods proxy?

Usage ideas:
* go.example.test <- vanity import "redirecting" to source code, docs or modules
* gp.example.test <- vanity proxy or module storage via athens aka on demand module storage

So go.example.test could link to gp.example.test, which then uses go.example.test to look up the source code and then caches the module. That is workable, but the question is does that make sense?

What are the various things that could be configured from a TXT record for gomods?
Wouldn't it be enough to provide gometa with gomods support and then a separate caddy plugin with gomods proxy support? Does it make sense to have a vanity url for gomods?

Another option later on would be:
So instead of being a passthrough cache it could save the modules on GCS or some other external storage reducing the load on the server.

proxy request -> gomods -> fetch source -> create modules -> save to GCS using data from `rec` -> redirect request to GCS module

And without a proxy gometa could be configured to either use the gomods proxy, that isn't using passthrough or just direct to the underlying GCS right away.

General workflows:
1. request -> gometa -> GCS (straight to storage)
2. request -> gometa -> gomods -> GCS (redirect to storage)
3. request -> gometa -> gomods (passthrough mode caching on the proxy)
4. proxy request -> gomods -> fetch -> save to GCS -> redirect (most likely done during build)

1. Would be possible with adding `mod` as new cvs
2. Would be possible with a new external cache mode, which could use the TXT record as GCS config
3. Currently possible. Not sure, if this makes sense as it doesn't use any TXT records and vanity url on gomodules might not be necessary as this is not exposed. All requests would still go through gometa anyway or am I missing something? Would we grab "go get gomods.example.test" instead of "go get gometa.example.test"? Not really I think.
4. Interesting feature, but needs private data, could be done within the build process, which seems a lot more sane and decentralized than pushing it through a central goproxy.

Option:
Split out gomods into it's own caddy plugin for internal or global company use, but remove from TXTDirect as it might not be needed to be bundled.

That ended up a lot more unclear than I thought. Still happy for any feedback, suggestions etc.
cc @erbesharat @alarsyo

**Comment by stp-ip** [comment]
Thinking on this further. There is an interesting option, where a vanity gomods proxy with sending to GCS might come in handy.
The global go proxy could be used in passthrough mode and depending on the url used copy packages into a separate storage. So every time a company specific proxy url is used the module that was used is externally archived. Either this archive is used on the next run (less bandwidth for us) or the passthrough is still used. This might be a good way to archive away used modules without integrating it into every developer action.

But it still seems a bit like this might not be the correct location for this type of config or process. It goes too far from the usual redirect/proxy idea perhaps.

**Comment by erbesharat** [comment]
Just a brief description of our previous conversations:

- The gomods proxy code that we have now should get migrated to another caddy plugin since there is no need to configure it using TXT records and also we don't need to start a full modules proxy.

- Add the support for "mod" vcs to gometa so we can have vanity URLs for go modules too.
- After implementing "mod" vcs we should add support for caching the Go modules that are served using gometa.

**Comment by erbesharat** [comment]
Also as we talked about the lightweight version of gomods, we can implement it after migrating the current code.

The lightweight version only redirects to the global Go modules proxy aka proxy.golang.org, and it enables the vanity URL support for modules.

**Comment by stp-ip** [comment]
Move gomods into its own repo.
gometa will get the ability to serve modules to speed up direct module pulls without a proxy.
