### ISSUE TITLE
[make] Iterate on makefile refactor

### ISSUE THREAD

**Issue by stp-ip** [txtdirect/txtdirect#194]
* [x] `make test`: Runs test on caddy-copy code, if `make build` was previously run.
* [x] `make build`: Failing build, if caddy-copy is already present. We should either clean it up or better only update the caddy-copy code.
* [x] `make image-build`: Fails without previous build run.
* [x] We don't do a full test run before deploying/pushing the container to GCR. One could have failing tests, but still build and deploy it.
* [x] `make docker-test` and `make docker-build` mount current directory and have issues, when `make build` or `make test` or `make docker-test` or `make docker-build` was run before aka when caddy-copy is still present.

What was your general routine to not run into the above issues? @erbesharat

**Comment by erbesharat** [comment]
I just had an alias that cd's into the project directory, removes caddy-copy then runs the build command so I didn't run into caddy-copy issue. Also, I didn't run `make build` on my local env so I didn't see it runs caddy's tests too.
