### ISSUE TITLE
[logfile] empty logfile config panics

### ISSUE THREAD

**Issue by stp-ip** [txtdirect/txtdirect#215]
**Is this a BUG REPORT or FEATURE REQUEST?**:
bug

**What happened**:
Setting logfile without anything panics.
```
txtdirect {
  enable host
  logfile
}
```

**What you expected to happen**:
Don't panic.

**Anything else we need to know?**:
Is this intended? What should we use as default?
Might be worth writing a test for.

**Comment by erbesharat** [comment]
I think setting `stdout` as the default value seems good.

**Comment by stp-ip** [comment]
Sounds good.
