### ISSUE TITLE
[header] Replace "server" header with "TXTDirect"

### ISSUE THREAD

**Issue by stp-ip** [txtdirect/txtdirect#221]
**Is this a BUG REPORT or FEATURE REQUEST?**:
feature

**What happened**:
When using caddy a server header is added "server: caddy".

**What you expected to happen**:
Rewrite header to "Server: TXTDirect".

**Comment by stp-ip** [comment]
Was trying for a way to work around this with a config, but it seems we might be impacting the header middleware somehow.

```
    :8080 {
      header / server TXTDirect
      txtdirect {
        enable host
      }
    }
```

This does not overwrite the header. Caddy bug or our bug?

**Comment by erbesharat** [comment]
@stp-ip It's not a bug, header config is case-sensitive, so `header / server` doesn't work.
Tested `header / Server TXTDirect` and it works fine.
Should we replace it inside our code too or using the config is ok?

**Comment by stp-ip** [comment]
Mhh thought I tried that, but seems like I didn't. Thanks for checking.

I think changing in Code is also a good idea. What do you think?

**Comment by erbesharat** [comment]
I think replacing the header in code is good too. Will create a PR for it.

**Comment by stp-ip** [comment]
Seems like we are only adding the header, but not replacing it. See `curl -v txtd.io`.

**Comment by stp-ip** [comment]
Configuration error. All good. Sorry for the noise.
