### ISSUE TITLE
[fallback] Add additional tests

### ISSUE THREAD

**Issue by stp-ip** [txtdirect/txtdirect#230]
**Is this a BUG REPORT or FEATURE REQUEST?**:
feature

**What happened**:
We are still running into fallback regressions.

**What you expected to happen**:
We need more tests.

**Anything else we need to know?**:
Test fallback, when only "www" or "host" enabled.

Currently enabling only "www" or "host" etc. results in a 500 error instead of the default redirect set globally.

**Comment by erbesharat** [comment]
Something about our fallback flow for host type doesn't feel right to me. We only trigger fallback for host when getBaseTarget() returns an error, then when we trigger the fallback we give it the `fallbackURL` variable which we have filled it using getBaseTarget().

https://github.com/txtdirect/txtdirect/blob/8774437eb24d0a14d1e62b538506d993f42e7bf5/txtdirect.go#L298-L303

https://github.com/txtdirect/txtdirect/blob/8774437eb24d0a14d1e62b538506d993f42e7bf5/txtdirect.go#L225

**Comment by stp-ip** [comment]
How would you think it should be?

My first guess is that we therefore don't set fallbackURL and due to it being missing aka getBaseTarget returning an error for both function calls it would trigger a fallback for an empty fallback and therefore to www. or redirect.

Definitely feels like a weird flow. We should go into the fallback function right away, if getBaseTarget fails I think.
Maybe we should generally rethink our fallback flow to make it easier to test as well. What do you think? Not sure yet, what makes the most sense for a refactor here.

**Comment by erbesharat** [comment]
Our fallback flow already works good for other types, `host` is the only one that's buggy. I think passing an empty string for fallbackURL just for this type is a better idea than a refactor. Or we can jump right to `c.Redirect` if the rec.Type is `host` instead of passing an empty string.

**Comment by stp-ip** [comment]
Ok let's go with an empty string first and reiterate later.
