### ISSUE TITLE
[idea] Create qr code for a short url

### ISSUE THREAD

**Issue by stp-ip** [txtdirect/txtdirect#258]
**Is this a BUG REPORT or FEATURE REQUEST?**:
feature

**What happened**:
Currently for offline campaigns etc. one need to manually create qr codes.

**What you expected to happen**:
Ability to easily get a qr code for a specific url with the help of a specific url or query key.

**Anything else we need to know?**:
Just a rough idea and might not be necessary in the short term.
Various shorteners yourls and shlink both have this feature.
Usually the add `.qr` on the path or something similar.

**Comment by erbesharat** [comment]
I really like this idea and think it would be good to have it since it wouldn't take a lot of time to implement.
+1 for `.qr`

**Comment by stp-ip** [comment]
Mhh thinking about it adding .qr might be more failure prone, but it seems to be the simplest.
The other option is to add a query string such as ?qr instead. That way it might collide less with general regexes, path and other types.

What do you think? Start with `?qr` and iterate from there?
