### ISSUE TITLE
[spec] Add spec validation/monitoring tool.

### ISSUE THREAD

**Issue by stp-ip** [txtdirect/txtdirect#263]
**Is this a BUG REPORT or FEATURE REQUEST?**:
feature

**What happened**:
Currently it's hard to monitor urls/redirects working correctly according to our spec.

**What you expected to happen**:
Make it possible for a tool to read in the DNS and validate the correct upstream address and conformance to our spec.

**Anything else we need to know?**:
Not sure on how to not reimplement txtdirect code for the monitoring tool so.

Maybe have a spec tool that reads in DNS text records and can validate, if and what version of our "spec" they conform to.
Better way to write a spec?
Monitoring tools usually can check the correct redirect so monitoring the redirect might not be necessary. Also it would be nice for a tool to read in a complete dns zone and then test conformance and monitor all URLs that are added there. That way we can confirm all urls still work as expected after a deploy or so.

Needs a lot more thoughts, but wanted to add the idea already.

**Comment by erbesharat** [comment]
I think we can first start with a tool that reads all the DNS records from a zonefile, sends a request for each zone and checks the Location header to see if the redirect URI matches the URI in the TXT record.
It can be a bit tricky for the types like dockerv2 which can have a non-specific endpoint, but I think we can tape that with some regex.
Then if we decide to introduce a newer record version (txtv1) we can add another option to the tool to look for the txtv1's fields and return the version of record.

**Comment by stp-ip** [comment]
I would go even simpler than this for now.
Basically just package up our parse function to be imported into a separate tool/cli.

Something along the lines of `txtdirect-validator <TXT record>`
This would check the TXT record for validity.

Additionally we could also check for specific values being correctly extracted:
`txtdirect-validator <TXT record> <key>=<value>`

But as an additional tool I would keep your idea handy. This might be a nice option to run as a small Go function or so to test an important redirect globally.
