### ISSUE TITLE
Overwrite Caddy version with TXTDirect version in -version command

### ISSUE THREAD

**Issue by stp-ip** [txtdirect/txtdirect#267]
**Is this a BUG REPORT or FEATURE REQUEST?**:
feature

**What happened**:
Currently we inherit the caddy version.

**What you expected to happen**:
Use TXTDirect version in builds.

**Anything else we need to know?**:
Already tried around a bit. Problem is caddy is using runtime information about the specific caddy module. Not sure we can really overwrite this.

**Comment by stp-ip** [comment]
https://golang.org/src/runtime/debug/mod.go?s=425:472#L7

**Comment by erbesharat** [comment]
I tried to change the version using `-ldflags` but we only can modify the [`appVersion`](https://github.com/mholt/caddy/blob/c0190a3460f7188db6ed2dc580fdf524b99261d0/caddy/caddymain/run.go#L588) variable. [`appName`](https://github.com/mholt/caddy/blob/c0190a3460f7188db6ed2dc580fdf524b99261d0/caddy/caddymain/run.go#L567) is const which results in `Caddy TXTDVERSION (unofficial)`

Also, I couldn't figure out how `debug.ReadBuildInfo()` is useful? It returned an empty struct.
