### ISSUE TITLE
Prevent gometa with "internal" in path

### ISSUE THREAD

**Issue by stp-ip** [txtdirect/txtdirect#27]
**Is this a BUG REPORT or FEATURE REQUEST?**:
feature

**What happened**:
Currently a folder path "internal" is not blacklisted.

**What you expected to happen**:
Internal should be blacklisted and therefore prevent working around the possibility to import internal packages.

**How to reproduce it (as minimally and precisely as possible)**:
Set a vanity import to an internal package.

**Anything else we need to know?**:
This is based on internal packages being introduced in 1.4 https://docs.google.com/document/d/1e8kOo3r51b2BWtTs_1uADIA5djfXhPT36s6eHVRIvaU

**Comment by alarsyo** [comment]
The go get tool doesn't enforce this itself when it is redirected to the real URL ?

**Comment by stp-ip** [comment]
It should be, but would there be any reason to allow a vanity on an internal package?
Cases:
We allow it and it won't get enforced by go get -> problem
We allow it and it gets enforced -> problem
Therefore I would say blacklisting and failing early before someone enables it and wonders why it's not working is a better approach.

**Comment by alarsyo** [comment]
That makes sense
