### ISSUE TITLE
[tests]: Discuss external E2E tests

### ISSUE THREAD

**Issue by erbesharat** [txtdirect/txtdirect#291]
**Is this a BUG REPORT or FEATURE REQUEST?**:
feature

**What happened**:
Currently, our E2E tests don't cover every part of the project and we need to have tests for more complex scenarios to be aware of the edge cases.

**What you expected to happen**:
Discuss how we're going to implement these tests and how the structure is supposed to be.

I think it would be good to have an isolated and fresh environment for each test case and keep all the records related to a test case inside its own zone file.
We can separate the test cases by keeping them in their own directories and have a manager script at the root that runs each test cases' script.
The structure would look like this:
```
├─e2e_tests
├── dockerv2
│   ├── pull
│   │   ├── zonefile
│   │   └── test.sh
│   └── push
│       ├── zonefile
│       └── test.sh
└── manager.sh
```

Not sure how we should handle the containers for each test case. We can use solutions like `compose` or have our own script for creating and managing the test containers.
I personally prefer the custom script and a downside would be requiring more time to implement a stable solution.
We can also add the container-related stuff to each test's script but think it would be better to keep the test script as clear and simple as possible and only keep the tests inside it.

Would love to hear other thoughts and approaches.

**How to reproduce it (as minimally and precisely as possible)**:
Feature Request

**Anything else we need to know?**:
Questions:
- A better structure for managing the files?
- Alternatives for compose and custom script?
- Other solutions for managing the test cases instead of a manager bash script?

**Comment by stp-ip** [comment]
This sounds like a great approach.

`e2e` directory split into `type` subdirectories with a specific zonefile and a test.sh is good.
Test.sh would then just call `curl/docker/<tool>` for each test case. One per line or something.

For the containers I would go without compose and let the manager.sh loop through the directories and start 2 containers. One with our txtdirect container (so that we are actually testing what we are building) and the other with a e2e testing container. Most likely the e2e container just needs curl/docker/git/go basically all client side tools that would call txtdirect.


> 
>     A better structure for managing the files?

Looks good already

>     Alternatives for compose and custom script?

Custom script should be fine and easy enough. Could always go with a small Go script later on.

>     Other solutions for managing the test cases instead of a manager bash script?

Nothing comes to mind. Selfwritten bash or Go script sounds good for now.

**Comment by stp-ip** [comment]
Basically use docker for the tools being called?
Have a go/bash script that calls each test case and the tool for each test case would be run through a docker container?
Something along the lines of `docker run -it c.txtdirect.org/testing -- git clone https://example.com` ?

I would probably run the whole test suite inside a docker container.
So the go/bash script would run within the test container. But maybe that's inconvenient.

Happy to hear your further thoughts.

**Comment by erbesharat** [comment]
We can start a container which is basically our "manager" container. It walks through the test directories using the manager-script and for each test-case runs an instance of txtdirect+corends (let's call it "tc"). All the tools we need for testing are installed in the manager container. The manager container then runs the test script for each test-case and only uses the tc container responsible for that test-case. And when test-case finishes, the tc container would get shut down and the manager container runs the new tc container for the next test-case.

Not sure about the cons of a docker-in-docker approach but at least this way we don't have to start a container and install a set of tools for every test-case.

**Comment by stp-ip** [comment]
I'll rehash the ideas and write up some more thoughts.
