### ISSUE TITLE
[tests]: Clear unused records from the zone map

### ISSUE THREAD

**Issue by erbesharat** [txtdirect/txtdirect#292]
**Is this a BUG REPORT or FEATURE REQUEST?**:
feature

**What happened**:
Currently, we have lots of unnecessary records in our zone map for E2E tests.
We should point all the URIs used inside the tests records to `example.com` since we right now none of the URIs follow a standard.

**What you expected to happen**:
Have a standard for all the URIs used inside the zone map and remove the unnecessary records.

**Anything else we need to know?**:
We should discuss this change before starting #291.
Should we still keep a minimal set of e2e tests inside our code or not? If we decide to keep a few of them then we have to still keep the mock DNS server too.
Also if we decide to move to only having external e2e tests, does it make sense to clear the records right now? I think since it takes much longer time to implement the external tests, it would worth it to clear the current records.

**Comment by stp-ip** [comment]
I agree on cleaning up our tests especially our use of URIs.

I would still keep a set of unit like tests with a mock dns server as it's easier to test. On the specifics I'll respond over at #291.

On the standardization how about the following for request records:
<test-case><specific-type>.<type>.example.com/<path>

Which get redirected to something like:
<reason><specific-type>.<type>.example.com

Example:
```
website-fallback.git.git.example.com
git-pull-success.git.git.example.com
git-push-success.git.git.example.com
wildcard-fallback.git.path.example.com
path-fallback.git.path.example.com
git-pull.git.path.example.com
git-push.git.path.example.com
```

A rough idea. Happy to hear your ideas.

**Comment by erbesharat** [comment]
I think this issue is fixed.
Current zone map: https://github.com/txtdirect/txtdirect/blob/master/txtdirect_test.go#L35-L46
