### ISSUE TITLE
[prometheus]: Metrics won't get registered and exporter doesn't start

### ISSUE THREAD

**Issue by erbesharat** [txtdirect/txtdirect#306]
**Is this a BUG REPORT or FEATURE REQUEST?**:
bug

**What happened**:
Prometheus exporter doesn't get started.

**What you expected to happen**:
Prometheus exporter to start successfully and register the metrics.

**How to reproduce it (as minimally and precisely as possible)**:
TXTDirect config:
```
txtdirect {
        enable host gometa path
        resolver 127.0.0.1:5353
        logfile stdout
        redirect 127.0.0.1
        prometheus
}
```
Prometheus Config:
```
global:
  scrape_interval:     15s
  evaluation_interval: 15s
scrape_configs:
  - job_name: 'txtdirect'
    static_configs:
    - targets: ['localhost:9183']
```

**Anything else we need to know?**:
Not sure if something is wrong with my setup or something got broken with the `go vet` changes. Still debugging, will update the issue when I find anything.

**Comment by stp-ip** [comment]
From a first look this seems correct on the config.

**Comment by stp-ip** [comment]
Yeah getting connection errors as well.

**Comment by stp-ip** [comment]
I think this could be the culprit: https://github.com/txtdirect/txtdirect/commit/1593301684c8dbf3db329aa38ba973110305f38e#diff-80babaafb537421e78f30d94e874bd6aR98
