### ISSUE TITLE
[header] Add header support to enable "HSTS Preload Support"

### ISSUE THREAD

**Issue by captn3m0** [txtdirect/txtdirect#308]
**Is this a BUG REPORT or FEATURE REQUEST?**: FEATURE REQUEST
bug | feature

**What happened**: I want to setup HSTS preload on a domain served by txtdirect.

**What you expected to happen**: A configuration option via DNS that lets me add HSTS Preload header.

**How to reproduce it (as minimally and precisely as possible)**: 

1. Setup a redirect using txtd.io
2. Check the header
3. No HSTS header

```
content-type: text/html; charset=utf-8
date: Thu, 19 Dec 2019 16:38:43 GMT
location: 
server: txtd.io
status-code: 302
x-sid: txtd.io-eb58fd
```

**Anything else we need to know?**: An HSTS header is a fairly basic security requirement today to prevent ISPs from blocking your website, and a HSTS preload header is required to prevent the redirect from being hijacked.

Ref:

- https://developer.mozilla.org/en-US/docs/Web/HTTP/Headers/Strict-Transport-Security
- https://hstspreload.org/

**Comment by stp-ip** [comment]
Various options on how to achieve this.
* add the HSTS header on all domains served by TXTDirect <- might be overreaching as not everyone might want this
* per record aka HSTS header opt-in value <- a lot of duplicated user config
* resolve the redirect and do some basic checks (headers, availability etc.) <- will slow down redirects

Thoughts?

cc. @erbesharat

**Comment by stp-ip** [comment]
Do be fair all requests going through txtd.io are https only and this assumption should hold over the long term.

So thinking about it I'm in favor of adding HSTS as a global option, which we can also turn on on txtd.io with a general warning.

**Comment by captn3m0** [comment]
I'd suggest:

1. Serve a short duration HSTS header (say a week) by default. Make sure this is documented so people switching elsewhere are aware of this.
2. Have an opt-in for HSTS preload, which ups the HSTS duration and adds the preload flag.

**Comment by stp-ip** [comment]
In which record would you expect the HSTS opt-in config to be?

**Comment by captn3m0** [comment]
Since HSTS applies to the entire domain, I'd like a domain-wide TXT record that reflects the intent here.

**Comment by stp-ip** [comment]
Unfortunately there is no precedent for using TXT for HSTS so we are on new territory on that front.
Checking a new record per request is problematic for latency and DNS query amounts.

The more this gets specced out it feels as if an opt-in "hsts=true" within the record would be the best way forward and will add the header without worrying about specific domain wide configuration.
So each single redirect type can add a "hsts=true" and if it is done through a "type=path" record that config takes precedent.

To enable preload we could have "hsts=true", "hsts=false" and "hsts=preload".

Still not perfectly happy with this yet.

**Comment by stp-ip** [comment]
Or we could go simpler and allow headers to be added:
```
>Strict-Transport-Security=max-age%3D63072000%3B+includeSubDomains%3B+preload+
```

That way each request could overwrite this. In the HSTS case not that useful, but using path would make all child records adhere to the path record set headers.

This feels like the most flexible and clean solution.

**Comment by stp-ip** [comment]
Downside is the urlencoding that would be necessary, but that's hard to workaround.

**Comment by captn3m0** [comment]
I like the header solution, would allow for some interesting stuff down the line.

**Comment by stp-ip** [comment]
Similar to how the `path` type currently works.

Setting it on the main record aka the one introducing `path` would be used first, but could be overwritten by any subsequent records. So zone wide not domain wide as we might not control the whole domain, but only a subsequent zone (subdomain).

1to1 relations such as using `host` or `git` without any `path` type involvement could be considered zone wide by itself.

Does that make sense?

**Comment by stp-ip** [comment]
Now globally live https://hstspreload.org/?domain=txtd.io
