### ISSUE TITLE
[make] make build should show dirty version

### ISSUE THREAD

**Issue by stp-ip** [txtdirect/txtdirect#328]
**Is this a BUG REPORT or FEATURE REQUEST?**:
bug

**What happened**:
`make  build` currently uses the latest version, but doesn't show the commit and a -dirty tag.
This might make it harder for us to catch, what version people are using as a development or modified version would still have the release version.

**What you expected to happen**:
`make build` should use a dirty version including commit info.
`make release`, if at all, should use the specific version. <- do we actually need this or we could split this up into a separate release make file.

**Comment by stp-ip** [comment]
CoreDNS example:
```
CoreDNS-1.5.2
linux/amd64, go1.12.7, a1377aeb-dirty
```

TXTDirect example:
```
TXTDirect-v0.4.1
linux/amd64, go1.13.5,
```

**Comment by erbesharat** [comment]
We already had the code for it but didn't pass the commit hash via -ldflags.

**Comment by erbesharat** [comment]
So I guess we wouldn't need `make release` since it would use the tag instead of the commit hash if it's available.

**Comment by stp-ip** [comment]
Yeah looks good as it is. Thanks for fixing it up.
