### ISSUE TITLE
[placeholders]: Default placeholders shouldn't overwrite custom placeholders

### ISSUE THREAD

**Issue by erbesharat** [txtdirect/txtdirect#333]
**Is this a BUG REPORT or FEATURE REQUEST?**:
bug

**What happened**:
Currently, the default placeholders would overwrite the named regex placeholders in case of a name collision.

**What you expected to happen**:
Use a new prefix for custom placeholders like named regex placeholders to avoid overwriting them.

**How to reproduce it (as minimally and precisely as possible)**:
Using the same names as default placeholders for named regex placeholder. like "host" and etc.

**Anything else we need to know?**:
What is the best prefix to use? suggestions:
- `{_my-named-regex}` "_"
- `{RE_my-named-regex}` "RE_"
- `{$my-named-regex}` "$"

**Environment**:
- TXTDirect version:  `master`

**Comment by erbesharat** [comment]
@stp-ip Which prefix do you think is better? Currently, we only need it for named regex placeholders but I think "$" would be a good option for custom placeholders in general since other projects like Nginx use it for placeholders too.

But if we're going to add more custom-named placeholders in the future, we might need to use different prefixes for them, so "RE_" seems like a better option in that case.

**Comment by stp-ip** [comment]
I think `$` is good.
Can't think of more placeholders that would be available at the same time as regex.
