### ISSUE TITLE
Rename txtdirect to TXTDirect

### ISSUE THREAD

**Issue by stp-ip** [txtdirect/txtdirect#36]
**Is this a BUG REPORT or FEATURE REQUEST?**:
feature

**What happened**:
We currently use txtdirect as name, but it comes up over and over again that TXTDirect feels more natural.

**Comment by alarsyo** [comment]
Trying to put up a list of places where the name needs to be changed:

- [ ] All automatically generated generated files
- [ ] The website
- [ ] Other websites ? (okkur, etc)

**Comment by stp-ip** [comment]
Logo
Okkur Website

That's it I think.

**Comment by stp-ip** [comment]
Will take a stab at the logo, when I have a few minutes next week.

**Comment by stp-ip** [comment]
Okkur and TXTDirect website can be done, when migrating to the latest Syna theme I assume.

**Comment by alarsyo** [comment]
Right. I'll do the documentation

**Comment by stp-ip** [comment]
Logo: https://3.basecamp.com/3920517/buckets/6109280/vaults/844848180
