### ISSUE TITLE
Log all requests served

### ISSUE THREAD

**Issue by alarsyo** [txtdirect/txtdirect#37]
**Is this a BUG REPORT or FEATURE REQUEST?**:
feature

**What happened:**
Especially with the failed implementation of the dockerv2 API, I think having a real log of each request processed and served would strongly benefit us for developping/debugging, and might be useful in production on the long term as well.

I guess caddy already logs incoming requests ? We probably need to record the redirects we send then, something like that. Thoughts ? Is it something that's already done for us completely in caddy, easily checked in real time from the built container ?

**Comment by stp-ip** [comment]
So caddy can log every request, but logging the specific redirect might be a bit harder. We can log the incoming URI, but for request placeholders there is nothing like {response}.
https://caddyserver.com/docs/log
https://caddyserver.com/docs/placeholders

**Comment by alarsyo** [comment]
Okay, so might as well have TXTDirect do all the logging anyway if we'll have to use it for logging redirects ? I didn't want it to be too noisy if caddy already handled everything but if we need to log SOME things ourselves anyway...

**Comment by stp-ip** [comment]
Haven't looked into it, but maybe there is a way to provide a new placeholder, which then can be used for custom logs?

**Comment by alarsyo** [comment]
I'll look up if something like this is possible

**Comment by stp-ip** [comment]
This should be optional.
