### ISSUE TITLE
Only first TXT record is checked

### ISSUE THREAD

**Issue by alarsyo** [txtdirect/txtdirect#40]
**Is this a BUG REPORT or FEATURE REQUEST?**:
bug

**What happened**:
TXTDirect fails if the DNS stores more than 1 record for a domain and the first one happens to not be the TXTDirect one.

**What you expected to happen**:
TXTDirect should look for a record it recognizes among all the TXT records for a domain

**How to reproduce it (as minimally and precisely as possible)**:
In addition to the TXT record needed for TXTDirect, register other TXT records on the same domain

**Comment by stp-ip** [comment]
I agree this might be a problem, but usually that's circumvented by using the _redirect subdomain. It's specific enough to prevent other TXT records on the same zone such as TXT records used for mail security.

What we definitely have is, when a _redirect. TXT record is provided twice it will only choose the first one. That could be seen as a user misconfiguration, but we probably should handle that better.

Another problem that we have is that, when a TXT record is too long, we only use the first snippet. We don't concatenate it into one. Question is, if we just add to the spec the maximum length of a _redirect record needs to be within one TXT record to circumvent this for now.
