### ISSUE TITLE
[path] Add custom regex option

### ISSUE THREAD

**Issue by stp-ip** [txtdirect/txtdirect#51]
**Is this a BUG REPORT or FEATURE REQUEST?**:
feature

**What happened**:
Currently the regex used to filter out the specific subzones/subdomains is hardcoded.

**What you expected to happen**:
Let the advanced user define the specific regex.
Path to be matched against: `12345-some-path?query=string&more=stuff`

**regex used for simplified version**
`re=([^/]*)`: _redirect.12345-some-path.example.com

**regex to extract page number**
`re=^(\d+)`: _redirect.12345.example.com

**regex to extract a single query string**
`re=\\?query=([^&]*)`: _redirect.string.example.com

**regex with numbered groups extracting 2 query strings**
`re=\\?query=(?P<2>[^&]+)\\&more=(?P<1>[^&]+)`: _redirect.string.more.example.com
Can't get the above to split it into 2 groups in Go. Have it working on https://regexr.com/ so.

`?P<1>` is used to name the group, which we could use for order.

**Comment by erbesharat** [comment]
@stp-ip Can you please check the first regex. If there is a query in the uri then the result would contain all the last path with the query inside it. For example with the first regex and the path "some-path/other-path?query=a" the result will be an array containing two items: "some-path" and "other-path?query=a". I don't think that's the correct result, is it?

**Comment by stp-ip** [comment]
The one for the simplified version should be the same as the one we hardcoded into the first iteration of path. Is that the one you meant?
