### ISSUE TITLE
Chaining type=path results in error

### ISSUE THREAD

**Issue by stp-ip** [txtdirect/txtdirect#59]
**Is this a BUG REPORT or FEATURE REQUEST?**:
bug

**What happened**:
Chaining multiple path routes together results in an error.

**What you expected to happen**:
Is it necessary to be supported?

```
_redirect             60 IN TXT     "v=txtv0;to=http://root.worked.example.test;default=http://default.worked.example.test;type=path;code=302"

_redirect.two.one     60 IN TXT     "v=txtv0;to=http://two-one.worked.example.test;type=path;code=302"
```
example.test/one/two -> _redirect.two.one.example.test -> error

**Environment**:
- TXTDirect version: master

**Comment by alarsyo** [comment]
Does it only happen with chaining ? Is it because the second redirection then reuses the `/one/two` path ?

**Comment by stp-ip** [comment]
It's due to path not being recursive I would say.

Flow:
* check zone
* check path
* path: follow zones (wildcards) to last record
* last record is path
* no futher path handle -> run into default "record type path not supported"
