### ISSUE TITLE
Document relative vs absolute url usage for "to="

### ISSUE THREAD

**Issue by stp-ip** [txtdirect/txtdirect#6]
To=about.example.com will redirect to vhost/about.example.com.

Either we need to document to actually add the protocol or we should default the protocol to https://, when there is no forward slash at the beginning.

Maybe parse the "to" value and see, if it's an address or just a path.

**Comment by alarsyo** [comment]
https://github.com/golang/go/blob/master/src/net/http/server.go#L1975

Go seems to consider this syntax as relative URLs, so maybe it'd be better to stick to the same behavior as the standard library, and expect an absolute URL ?

I'd rather do that than go against the standard, but if you prefer to simplify the syntax then sure we could just check for a slash

(calling url.Parse on "about.something.com" returns a url with just a path, no hostname)

**Comment by stp-ip** [comment]
Ok so we can consider it a configuration error.
Absolute urls and everything else is relative. Let's document that.

**Comment by alarsyo** [comment]
How should we document this ? Start writing some documentation for the whole package ?

**Comment by stp-ip** [comment]
I'll add the base files via reposeed in the coming days so we have a base to work with. Then we can add the documentation.
