### ISSUE TITLE
Document that arbitrary key/value pairs are allowed

### ISSUE THREAD

**Issue by alarsyo** [txtdirect/txtdirect#63]
**Is this a BUG REPORT or FEATURE REQUEST?**:
feature

Arbitrary key/value pairs should just be discarded (this allows to upgrade TXT records in case a newer version of TXTDirect uses new keys, without breaking older versions)

Arbitrary data, however, shouldn't be allowed. (except for the `to=` URL)

Summary:
```
v=txtv0;to=https://txtdirect.org;code=302 -> works
v=txtv0;https://txtdirect.org;code=302 -> works
v=txtv0;to=https://txtdirect.org;code=302;tracking=true -> works
v=txtv0;https://txtdirect.org;302 -> fails
v=txtv0;to=https://txtdirect.org;302 -> fails
```

**Comment by stp-ip** [comment]
We are logging arbitrary data usage and don't allow URL definitions without `to=` key anymore. Basically we are defaulting to being strict.
