### ISSUE TITLE
Fallback defaults to www. redirect

### ISSUE THREAD

**Issue by stp-ip** [txtdirect/txtdirect#67]
**Is this a BUG REPORT or FEATURE REQUEST?**:
bug

**What happened**:
When rec.To isn't provided it will redirect using "www." without checking if that is disabled within the config.

**What you expected to happen**:
Handle a missing rec.To differently, if `disable www`.
Also we have the defaulting of www twice. Once in `Parse` and once as a default redirect in `Redirect`. Might be better combined?

**Environment**:
- TXTDirect version: master

**Comment by erbesharat** [comment]
I can't understand what we expect to happen correctly. Can you describe it more?

**Comment by stp-ip** [comment]
With a configuration:
```
txtdirect {
  enable path host
}
```
This means `www` type is disabled. When no url is provided `to=` then currently we might fallback to adding `www.` to the host and redirecting there. This is done without checking, if the type is actually enabled or disabled. It should take the configuration into account and either use the `www` redirect or not.

**Comment by erbesharat** [comment]
You mean we should directly go to 404 if `www` is disabled?

**Comment by stp-ip** [comment]
I assume so yeah.

**Comment by erbesharat** [comment]
Fixed in #73
