### ISSUE TITLE
Index out of range error when "from" doesn't match number of directories

### ISSUE THREAD

**Issue by stp-ip** [txtdirect/txtdirect#69]
**Is this a BUG REPORT or FEATURE REQUEST?**:
bug

**What happened**:
We currently experience a 500 error, when the number of directories from `from=` and the number of directories in `path` doesn't match.

**What you expected to happen**:
1. Don't fail with a 500 error
2. At least fallback the various fallback redirects
3. Might need more thinking in the long run

**Environment**:
- TXTDirect version: master

**Comment by erbesharat** [comment]
We can return an error for now and trigger the fallback code until we find a better solution.

**Comment by stp-ip** [comment]
Ok let's log an error and trigger the fallback redirect.
Sounds like a good solution. We can add a revisit label after it's closed and look into it later again.

**Comment by stp-ip** [comment]
This seems to have resurfaced. Probably we should add a test.

Error: "path.go:65 - runtime error: index out of range"
