### ISSUE TITLE
[placeholder] Implement more placeholders

### ISSUE THREAD

**Issue by stp-ip** [txtdirect/txtdirect#90]
**Is this a BUG REPORT or FEATURE REQUEST?**:
bug | feature

**What happened**:
Currently we started with {uri} as the first placeholder.

**What you expected to happen**:
Implement more placeholders. Might need a few thoughts especially around encoding.
{~cookie} | The value of a cookie, where "cookie" is the cookie name
{dir} | The directory of the requested file (from request URI)
{file} | The name of the requested file (from request URI)
{fragment} | The last part of the URL starting with "#"
{>Header} | Any request header, where "Header" is the header field name
{host} | The host value on the request
{hostonly} | Same as {host} but without port information
{method} | The request method (GET, POST, etc.)
{path} | The path portion of the original request URI (does not include query string or fragment)
{path_escaped} | Query-escaped variant of {path}
{port} | The client's port
{query} | The query string portion of the URL, without leading "?"
{query_escaped} | The query-escaped variant of {query}
{?key} | The value of the "key" argument from the query string
{uri} | The request URI (includes path, query string, and fragment)
{uri_escaped} | The query-escaped variant of {uri}
{user} | The username authorized by basicauth (HTTP Basic Authentication)

**Comment by erbesharat** [comment]
Do we only need these placeholders in ``rec.To`` for now till we work on #91?

**Comment by stp-ip** [comment]
I would say this would only be necessary in rec.To, if I haven't missed anything. They are provided/extracted by caddy and rec.To can work with them.
