### ISSUE TITLE
[log] shorten time object something like "YYYY-MM-DDT18:05:58Z"

### ISSUE THREAD

**Issue by stp-ip** [txtdirect/txtdirect#95]
**What happened**:
Currently the time is not consistent with caddy logging and other logging frameworks.

**What you expected to happen**:
Shorten it to year and time.

**Comment by erbesharat** [comment]
Caddy is using this format: ``02/Jan/2006:15:04:05 -0700``
Should we use it too?

**Comment by stp-ip** [comment]
Ok wow I had something else in my head. I would prefer we use the ISO standard for the date and time, but let's be consistent with Caddy for now.

So I'm seeing this currently:
```
2018/08/17 22:44:06 <2018-08-17 22:44:06.83284041 +0000 UTC m=+5.171444163> [txtdirect]: /favicon.ico > example.test:8080/favicon.ico
```
Basically a double date+time. I would have assumed only one. We can go with the caddy format, but shouldn't duplicate the information.
